sudo: false
language: scala
scala:
  - 2.11.12
jdk:
  - oraclejdk8
script:
  - sbt clean +test
  - sbt coverage reactifyJVM/test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete