os: linux
dist: bionic
language: scala
jdk:
  - openjdk8
script:
  - sbt +clean +reactifyJVM/test +reactifyJS/test +reactifyNative/test
  - sbt coverage reactifyJVM/test
  - sbt coverageAggregate
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --skip
cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.cache/codacy
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.sbt -name "*.lock" -delete
