language: scala
sudo: required
dist: trusty
scala:
  - 2.13.1
jdk:
  - oraclejdk8
before_script:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
script:
  - sbt +clean +reactifyJVM/test +reactifyJS/test ++2.11.12 reactifyNative/test
  - sbt coverage reactifyJVM/test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
