version: ~> 1.0
import: scala/scala-dev:travis/default.yml
language: scala
scala:
  - 2.13.5
env:
  - ADOPTOPENJDK=8     SCALAJS_VERSION=1.5.0  CACHE_WORKAROUND=see-PR-335
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 14
  - nvm use 14
  - git fetch --tags
script:
  - sbt clean test
  - sbt coverage coreJVM/test fileModuleJVM/test slf4j/test slf4j18/test
  - sbt coverageReport
  - sbt coverageAggregate
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --skip
notifications:
  email:
    - matt@matthicks.com